name: CodeSentinel Security Scan

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tool_requirements.txt

    - name: Run CodeSentinel Scan & Remediation Agent
      # This is the only part that changes
      env:
        GITHUB_PAT: ${{ secrets.CODESENTINEL_PAT }}
      run: |
        python main.py --ci-mode --file requirements.txt --threshold 80
